#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ww_p34_gen_overrides_logic_test.py --- machine-behaviour logic test for
scripts/ww_p34_gen_overrides.py (P34.3 auto-override generator).

ASSERTS MACHINE BEHAVIOUR ONLY.  All rows/series are SYNTHETIC fixtures; they
are NOT real WickedWhims/P34 data and never claimed to be.  Proves that:

  * looks_like_target matches ONLY rows whose raw_display_name contains the
    'NOT Caught Cheating' marker (case-insensitive) and nothing else;
  * derive_zh maps every member to the single canonical stem 未被捉奸 plus its
    own numeral / ' - <suffix zh>' / '*自定义声音*' tail (operator examples 1 and
    8 - Climax -> 未被捉奸 8 - 高潮; *CUSTOM VOICES* -> *自定义声音*);
  * unknown beat suffixes are dropped, never mis-glossed / never fabricated;
  * gen_overrides reuses identifier VERBATIM and sets reason/note exactly;
  * the override CSV it WRITES is UTF-8 **with BOM** and round-trips through
    read_overrides (ww_p34_build_final) as (identifier -> translated_name);
  * end-to-end: n2-shape mapping (whose S00317 members are LLM-divergent) +
    an override generated by THIS script -> ww_p34_build_final -> the final
    mapping passes ww_p34_spotcheck INV5 and the ww_p34_encoding_gate.
"""
from __future__ import print_function
import ast
import csv
import os
import sys
import tempfile

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
import ww_p34_gen_overrides as G       # noqa: E402
import ww_p34_build_final as BF        # noqa: E402
import ww_p34_encoding_gate as EG      # noqa: E402
import ww_p34_spotcheck as SC          # noqa: E402

_PASS = []


def _assert(cond, msg):
    if not cond:
        raise AssertionError(msg)
    _PASS.append(msg)


def _tmp(name):
    return os.path.join(tempfile.mkdtemp(prefix="p34go_"), name)


def _row(o, i, raw, zh):
    return {"source_instance": "0x43F3438A94EDEB2B", "ordinal": str(o),
            "identifier": i, "raw_display_name": raw, "translated_name": zh,
            "status": "TRANSLATED", "note": ""}


def test_py37():
    for f in ("ww_p34_gen_overrides.py", "ww_p34_gen_overrides_logic_test.py"):
        src = open(os.path.join(_HERE, f), encoding="utf-8").read()
        ast.parse(src, feature_version=(3, 7))
        _assert(True, "py37 parse PASS %s" % f)


def test_looks_like_target():
    _assert(G.looks_like_target("NOT Caught Cheating 1"), "upper target yes")
    _assert(G.looks_like_target("not caught cheating 2"), "lower target yes")
    _assert(G.looks_like_target("NOT CAUGHT CHEATING 3 - AfterSex"), "anycase yes")
    _assert(not G.looks_like_target("Kiss 1"), "Kiss family excluded")
    _assert(not G.looks_like_target("All Yours 2 - Creampie"), "All Yours excl")
    _assert(not G.looks_like_target(""), "empty excluded")
    _assert(not G.looks_like_target("Cheating on the Exam 4"), "not a marker lookup")


def test_derive_operator_examples():
    exp = {
        "NOT Caught Cheating 1": "未被捉奸 1",
        "NOT Caught Cheating 8 - Climax": "未被捉奸 8 - 高潮",
        "NOT Caught Cheating 3 *CUSTOM VOICES*": "未被捉奸 3 *自定义声音*",
        "NOT Caught Cheating 4 - Intro": "未被捉奸 4 - 开场",
        "NOT Caught Cheating 2 - AfterSex": "未被捉奸 2 - 后戏",
    }
    for raw, want in exp.items():
        _assert(G.derive_zh(raw) == want,
                "derive %r == %r (got %r)" % (raw, want, G.derive_zh(raw)))


def test_derive_custom_voices_with_suffix():
    got = G.derive_zh("NOT Caught Cheating 5 - Climax *CUSTOM VOICES*")
    _assert(got == "未被捉奸 5 - 高潮 *自定义声音*", "custom voices + climax as suffix")


def test_derive_all_share_one_stem():
    stems = {G.derive_zh(r).split(" ")[0]
             for r in ["NOT Caught Cheating 1",
                       "NOT Caught Cheating 2 - AfterSex",
                       "NOT Caught Cheating 8 - Climax",
                       "NOT Caught Cheating 6 *CUSTOM VOICES*"]}
    _assert(stems == {"未被捉奸"},
            "every derived member shares ONE zh stem (INV5 prerequisite)")


def test_derive_unknown_suffix_not_fabricated():
    # 'Cumshot' is not in SUFFIX_ZH -> drop it, keep stem, never invent a gloss
    _assert(G.derive_zh("NOT Caught Cheating 7 - Cumshot") == "未被捉奸 7",
            "unknown beat suffix dropped (fail-closed, stem still unified)")


def test_gen_overrides_reuse_identifier_and_verbatim_raw():
    rows = [
        _row(317, "idAAA", "NOT Caught Cheating 1", "未被捉奸"),
        _row(318, "idBBB", "NOT Caught Cheating 2", "没被发现"),
        _row(1, "kiss1", "Kiss 1", "接吻 1"),
    ]
    ov = G.gen_overrides(rows)
    _assert(len(ov) == 2, "only 2 NOT-Caught targets (Kiss excluded)")
    ids = {o["identifier"] for o in ov}
    _assert(ids == {"idAAA", "idBBB"}, "identifiers reused verbatim")
    _assert(all(o["reason"] == "series consistency" for o in ov), "reason col set")
    _assert(all(o["note"] == "Not Caught Cheating" for o in ov), "note col set")


def test_write_overrides_is_bom_and_roundtrips():
    p = _tmp("overrides.csv")
    ov = [{"identifier": "idAAA", "translated_name": "未被捉奸 1",
           "reason": "series consistency", "note": "Not Caught Cheating"}]
    G.write_overrides(p, ov)
    with open(p, "rb") as fh:
        _assert(fh.read(3) == EG.BOM, "override CSV written with UTF-8 BOM")
    back, scanned = BF.read_overrides(p)
    _assert(back == {"idAAA": "未被捉奸 1"} and scanned == 1,
            "reflects csv -> read_overrides (identifier -> translated_name)")


def _write_mapping(path, rows, bom=True):
    with open(path, "w", encoding=("utf-8-sig" if bom else "utf-8"),
              newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=BF.MAP_COLS, extrasaction="ignore",
                           lineterminator="\n")
        w.writeheader()
        for r in rows:
            w.writerow(r)


def test_end_to_end_inv5_closed():
    """n2-like mapping with an LLM-divergent S00317-ish family; auto-generate the
    override (this script) -> build_final -> spotcheck must reach INV5 PASS."""
    rows = [
        # the trouble series: divergent stems with no pivot
        _row(317, "d317", "NOT Caught Cheating 1", "未被捉奸"),
        _row(318, "d318", "NOT Caught Cheating 2", "没被发现"),
        # an already-canonical multi-member family (control)
        _row(3, "ay1", "All Yours 1 - Creampie", "全给你 1 - 射精"),
        _row(4, "ay2", "All Yours 2 - Creampie", "全给你 2 - 射精"),
        # a divergent suffix one we do NOT override (stays as-is; builds a
        # NON-NOT-target family so it must already be fine or be skipped)
        _row(9, "s1", "Reckless", "放荡之夜"),
    ]
    inp = _tmp("n2_clean.csv")
    _write_mapping(inp, rows)

    # context CSV for series grouping (spotcheck needs it)
    ctx_rows = [
        ("d317", "NOT Caught Cheating 1", "S00317", "1", ""),
        ("d318", "NOT Caught Cheating 2", "S00317", "2", ""),
        ("ay1", "All Yours 1 - Creampie", "S00003", "1", "Creampie"),
        ("ay2", "All Yours 2 - Creampie", "S00003", "2", "Creampie"),
        ("s1", "Reckless", "", "", ""),
    ]
    ctxp = _tmp("ctx.csv")
    with open(ctxp, "w", encoding="utf-8-sig", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["identifier", "raw_display_name", "series_key",
                    "title_sequence_token", "title_suffix"])
        w.writerows(ctx_rows)

    # 0) spotcheck BEFORE override must FAIL on the divergent family
    series_map, src_map = SC.load_series_csv(ctxp)
    fails0, _, _ = SC.spotcheck(SC.load_mapping(inp), expect_rows=len(rows),
                                series_map=series_map, src_map=src_map)
    _assert(any("S00317" in f for f in fails0),
            "pre-override INV5 flags the S00317 family")

    # 1) generate overrides deterministically from the mapping itself
    ov_file = _tmp("overrides.csv")
    ov_rows = G.gen_overrides(SC.load_mapping(inp))
    _assert(len(ov_rows) == 2, "override generator produced exactly 2 rows")
    G.write_overrides(ov_file, ov_rows)

    # 2) build final applying those overrides
    final = _tmp("final.csv")
    rc = BF.main([inp, "--overrides", ov_file, "--out", final])
    _assert(rc == 0, "build_final rc 0 after auto overrides")

    # 3) spotcheck final: INV5 must PASS, INV2 (raw byte-for-byte) must hold
    fails, _, _ = SC.spotcheck(SC.load_mapping(final), expect_rows=len(rows),
                               series_map=series_map, src_map=src_map)
    _assert(not fails, "final mapping passes ALL spotcheck invariants (got %s)"
            % fails)

    # 4) encoding gate on the final file
    stEnc, _, _ = EG.audit_file(final)
    _assert(stEnc == "PASS",
            "final mapping passes the ENCODING gate (BOM + clean utf-8)")


def main():
    test_py37()
    test_looks_like_target()
    test_derive_operator_examples()
    test_derive_custom_voices_with_suffix()
    test_derive_all_share_one_stem()
    test_derive_unknown_suffix_not_fabricated()
    test_gen_overrides_reuse_identifier_and_verbatim_raw()
    test_write_overrides_is_bom_and_roundtrips()
    test_end_to_end_inv5_closed()
    print("CHECKS_PASSED=%d/%d" % (len(_PASS), len(_PASS)))
    print("=" * 60)


if __name__ == "__main__":
    main()
